version: "3.9"
services:
  mongo:
    image: mongo:6-jammy
    container_name: icey-mongo-rs
    command: ["--replSet", "rs0", "--bind_ip_all"]
    ports:
      - "27017:27017"
    volumes:
      - icey-mongo-rs-data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 3s
      retries: 30

volumes:
  icey-mongo-rs-data:
